use_frameworks!
platform :ios, '9.0'

target 'JQCollectionViewWaterfallLayout_Example' do
  pod 'JQCollectionViewWaterfallLayout', :path => '../'

  target 'JQCollectionViewWaterfallLayout_Tests' do
    inherit! :search_paths

  end
end
